# SPDX-FileCopyrightText: 2023 Alec Delaney
# SPDX-License-Identifier: MIT

name: 'Issue Labeled Ping'
description: 'Notify a specified user when a specific label is applied'
author: Alec "tekktrik" Delaney

branding:
  icon: 'at-sign'
  color: 'blue'


inputs:
  github-token:
    description:
      The GitHub token needed to authenticate, must have write permessions
      for issues
    required: true
  user:
    description: 'The user to notify'
    required: true
  label:
    description: 'The label to monitor'
    required: true
  message:
    description:
      The message to write; {user} and {label} will be populated with the
      above fields, with {user} tagging the specified user.  If the message
      does not include {user}, then '{user} - ' will be included at the
      start of the message.
    default: '{user} - "{label}" label was applied.'
  assign-to-user:
    description:
      Assign the issue to the requested user as well.  Can be either "true"
      or "false" (default is false).
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      shell: bash
      run: pipx install uv
    - name: Install the required version on python
      shell: bash
      run: uv python install --project ${{ github.action_path }}
    - name: Run the label checking action
      shell: bash
      run: uv run ${{ github.action_path }}/action.py
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_USER: ${{ inputs.user }}
        INPUT_LABEL: ${{ inputs.label }}
        INPUT_MESSAGE: ${{ inputs.message }}
        INPUT_ASSIGN_TO_USER: ${{ inputs.assign-to-user }}
        ACTION_REPO: ${{ github.repository }}
        ACTION_EVENT_PATH: ${{ github.event_path }}
