# SPDX-FileCopyrightText: 2023 Alec Delaney
# SPDX-License-Identifier: MIT

name: 'Issue Labeled Ping'
description: 'Notify a specified user when a specific label is applied'
author: Alec "tekktrik" Delaney

branding:
  icon: 'at-sign'
  color: 'blue'


inputs:
  github-token:
    description:
      The GitHub token needed to authenticate, must have write permessions
      for issues
    required: true
  user:
    description: 'The user to notify'
    required: true
  label:
    description: 'The label to monitor'
    required: true
  message:
    description:
      The message to write; {user} and {label} will be populated with the
      above fields, with {user} tagging the specified user.  If the message
      does not include {user}, then '{user} - ' will be included at the
      start of the message.
    default: '{user} - "{label}" label was applied.'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      run: pipx install uv
    - name: Install the required version on python
      run: uv python install --project ${{ github.action_path }}
    - name: Run the label checking action
      run: uv run ${{ github.action_path }}/action.py
